/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.Koneksi;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rizkytanjung
 */
public class FormDataJaminan extends javax.swing.JFrame {

    /**
     * Creates new form FDataBarang
     */
    private DefaultTableModel tabmode;
    Connection conn = new Koneksi().getConnection();

    NumberFormat numberFormat = NumberFormat.getNumberInstance(new Locale("in", "ID"));

    public FormDataJaminan() {
        initComponents();

        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen.width, screen.height);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        view_data();

//        list_data_jaminan();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_kode_jaminan = new javax.swing.JTextField();
        t_nama_jaminan = new javax.swing.JTextField();
        b_save = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        b_refresh_table = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_data_jaminan = new javax.swing.JTable();
        b_search = new javax.swing.JButton();
        t_search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        b_edit = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(237, 229, 252));

        jPanel1.setBackground(new java.awt.Color(28, 64, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 46));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA JAMINAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jLabel3.setText("Kode Jaminan");

        jLabel4.setText("Nama Jaminan");

        t_kode_jaminan.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        t_nama_jaminan.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        b_save.setText("SAVE");
        b_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });

        b_cancel.setText("CANCEL");
        b_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        b_refresh_table.setText("Refresh Table");
        b_refresh_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_refresh_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_refresh_tableActionPerformed(evt);
            }
        });

        tbl_data_jaminan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data_jaminan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_data_jaminanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_data_jaminan);

        b_search.setText("Search");
        b_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_searchActionPerformed(evt);
            }
        });

        t_search.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        t_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_searchKeyTyped(evt);
            }
        });

        b_edit.setText("Edit");
        b_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editActionPerformed(evt);
            }
        });

        b_delete.setText("Delete");
        b_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(t_nama_jaminan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(t_kode_jaminan))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(b_search, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_search))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_refresh_table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b_save, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(t_kode_jaminan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(t_nama_jaminan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(b_refresh_table, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(b_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(b_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_search)
                                    .addComponent(t_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String id_user, nama_user;

    private void justNumber(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }

    private void reset_text() {
        t_kode_jaminan.setText("");
        t_nama_jaminan.setText("");
    }

    private void view_data() {
        Object[] baris = {
            "Kode Jaminan",
            "Nama Jaminan"
        };
        tabmode = new DefaultTableModel(null, baris);
        tbl_data_jaminan.setModel(tabmode);
        String search;
        if ("".equals(t_search.getText())) {
            search = "";
        } else {
            search = t_search.getText();
        }
        try {
            String sql = "SELECT * FROM tb_data_jaminan"
                    + " WHERE kode_jaminan LIKE '%" + search + "%'"
                    + " OR nama_jaminan LIKE '%" + search + "%'"
                    + " ORDER BY kode_jaminan ASC";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String kode = hasil.getString("kode_jaminan");
                String nama = hasil.getString("nama_jaminan");
                String[] data = {
                    kode,
                    nama
                };
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL\n" + e, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }

//    private void list_data_jaminan() {
//        t_kode_jaminan.removeAllItems();
//        try {
//            String sql = "SELECT *"
//                    + " FROM tb_data_jaminan"
//                    + " ORDER BY kode_jaminan ASC";
//            Statement stat = conn.createStatement();
//            ResultSet hasil = stat.executeQuery(sql);
//            t_kode_jaminan.addItem("--Pilih--");
//            while (hasil.next()) {
//                String kode = hasil.getString("kode_jaminan");
//                t_kode_jaminan.addItem(kode);
//            }
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, "Kode Jaminan TIDAK DITEMUKAN.\n" + e, "Info", JOptionPane.INFORMATION_MESSAGE);
//        }
//    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        FUtama FormUtama = new FUtama();
        FormUtama.l_id_user.setText(id_user);
        FormUtama.l_nama_user.setText(nama_user);
        FormUtama.setVisible(true);
        this.setVisible(false);
//        JOptionPane.showMessageDialog(null, "Closing DISINI!","Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_formWindowClosing

    private void save_data() {
        try {
            String sql = "INSERT INTO tb_data_jaminan VALUES"
                    + "("
                    + "?,"
                    + "?"
                    + ")";
            PreparedStatement stat;
            stat = conn.prepareStatement(sql);
            stat.setString(1, t_kode_jaminan.getText());
            stat.setString(2, t_nama_jaminan.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL", "Info", JOptionPane.INFORMATION_MESSAGE);
            view_data();
            reset_text();
            t_kode_jaminan.requestFocus();
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL.\n" + se, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void update_data() {
        try {
            String sql = "UPDATE tb_data_jaminan set "
                    + "nama_jaminan=?"
                    + " WHERE kode_jaminan='" + t_kode_jaminan.getText() + "'";
            PreparedStatement stat;
            stat = conn.prepareStatement(sql);
            stat.setString(1, t_nama_jaminan.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update data BERHASIL", "Info", JOptionPane.INFORMATION_MESSAGE);
            b_save.setText("SAVE");
            t_kode_jaminan.setEditable(true);
            t_kode_jaminan.setBackground(new java.awt.Color(255, 255, 255));
            reset_text();
            view_data();
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, "Update data GAGAL\n " + se, "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        // TODO add your handling code here:
        if ("".equals(t_kode_jaminan.getText())) {
            JOptionPane.showMessageDialog(null, "Kode Jaminan BELUM DIISI!", "Info", JOptionPane.INFORMATION_MESSAGE);
            t_kode_jaminan.requestFocus();
        } else {
            if ("SAVE".equals(b_save.getText())) {
                String sql = "SELECT * FROM tb_data_jaminan WHERE kode_jaminan='" + t_kode_jaminan.getText() + "'";
                try {
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Kode Jaminan " + t_kode_jaminan.getText() + " SUDAH ADA!", "Info", JOptionPane.INFORMATION_MESSAGE);
                        t_kode_jaminan.requestFocus();
                    } else {
                        save_data();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Cek duplikat kode jaminan GAGAL! \n" + e);
                }
            } else {
                update_data();
            }
        }
    }//GEN-LAST:event_b_saveActionPerformed

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        // TODO add your handling code here:
        b_save.setText("SAVE");
        t_kode_jaminan.setEditable(true);
        t_kode_jaminan.setBackground(new java.awt.Color(255, 255, 255));
        reset_text();
    }//GEN-LAST:event_b_cancelActionPerformed

    private void b_refresh_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_refresh_tableActionPerformed
        // TODO add your handling code here:
        view_data();
    }//GEN-LAST:event_b_refresh_tableActionPerformed

    private void search_data_jaminan() {
        String sql = ""
                + " SELECT *"
                + " FROM tb_data_jaminan"
                + " WHERE kode_jaminan='" + t_kode_jaminan.getText() + "'";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                //t_penulis.setSelectedItem(rs.getString("tipe_kamar"));
//                t_nama.setText(rs.getString("nama_jaminan"));
//                t_no_tlp.setText(rs.getString("no_tlp_jaminan"));
//                t_alamat.setText(rs.getString("alamat_jaminan"));
                t_kode_jaminan.setText(rs.getString("kode_jaminan"));
            } else {
                JOptionPane.showMessageDialog(null, "Data Barang TIDAK DITEMUKAN", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Pencarian Data jaminan GAGAL! \n" + e, "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void b_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editActionPerformed
        // TODO add your handling code here:

        int row_count = tbl_data_jaminan.getRowCount();

        if (row_count <= 0) {
            JOptionPane.showMessageDialog(null, "Data yang akan diedit KOSONG!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int baris = tbl_data_jaminan.getSelectedRow();
            if (baris < 0) {
                JOptionPane.showMessageDialog(null, "Data yang akan diedit BELUM DIPILIH!", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String kode = (String) tbl_data_jaminan.getValueAt(baris, 0);
                String nama = (String) tbl_data_jaminan.getValueAt(baris, 1);
                b_save.setText("UPDATE");
                t_kode_jaminan.setText(kode);
                t_nama_jaminan.setText(nama);
                t_kode_jaminan.setEditable(false);
                t_kode_jaminan.setBackground(new java.awt.Color(237, 229, 252));
                t_kode_jaminan.requestFocus();
                search_data_jaminan();
            }
        }
    }//GEN-LAST:event_b_editActionPerformed

    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
        // TODO add your handling code here:
        int row_count = tbl_data_jaminan.getRowCount();

        if (row_count <= 0) {
            JOptionPane.showMessageDialog(null, "Data yang akan dihapus KOSONG!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int baris = tbl_data_jaminan.getSelectedRow();
            //JOptionPane.showMessageDialog(null,"Baris dipilih "+baris,"Info", JOptionPane.INFORMATION_MESSAGE);
            if (baris < 0) {
                JOptionPane.showMessageDialog(null, "Data yang akan dihapus BELUM DIPILIH!", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String kode = (String) tbl_data_jaminan.getValueAt(baris, 0);
                int ok = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data: " + kode + " ini..?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (ok == 0) {
                    try {
                        //panggil method koneksi
                        String sql = "DELETE FROM tb_data_jaminan WHERE kode_jaminan ='" + kode + "'";
                        Statement st = conn.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Menghapus data BERHASIL", "Info", JOptionPane.INFORMATION_MESSAGE);
                        view_data();
                    } catch (HeadlessException | SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Meghapus data GAGAL" + ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_b_deleteActionPerformed

    private void b_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_searchActionPerformed
        // TODO add your handling code here:
        view_data();
    }//GEN-LAST:event_b_searchActionPerformed

    private void t_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_searchKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            view_data();
        }
    }//GEN-LAST:event_t_searchKeyTyped


    private void tbl_data_jaminanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_data_jaminanMouseClicked
//        int bar = tbl_data_jaminan.getSelectedRow();
//        String a = tabmode.getValueAt(bar, 0).toString();
//        String b = tabmode.getValueAt(bar, 1).toString();
//        String c = tabmode.getValueAt(bar, 2).toString();
//        String d = tabmode.getValueAt(bar, 3).toString();
//        String e = tabmode.getValueAt(bar, 4).toString();
//        String f = tabmode.getValueAt(bar, 5).toString();
//        t_kode.setText(a);
//        t_nama.setText(b);
//        c_kode_barang.setSelectedItem(c);
//        t_nama_barang.setText(d);
//        t_no_tlp.setText(e);
//        t_alamat.setText(f);
    }//GEN-LAST:event_tbl_data_jaminanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataJaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormDataJaminan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_edit;
    private javax.swing.JButton b_refresh_table;
    private javax.swing.JButton b_save;
    private javax.swing.JButton b_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t_kode_jaminan;
    private javax.swing.JTextField t_nama_jaminan;
    private javax.swing.JTextField t_search;
    private javax.swing.JTable tbl_data_jaminan;
    // End of variables declaration//GEN-END:variables
}
